CREATE TABLE IF NOT EXISTS users (
    id       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email    TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role     TEXT NOT NULL DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS tasks (
    id      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title   TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id)
);